package com.application.echo.ui.components.flags

import androidx.annotation.DrawableRes
import com.application.echo.ui.design.R

object FlagDrawable {

    @DrawableRes
    fun forIso(isoCode: String): Int = when (isoCode.lowercase()) {
        FlagIso.AF -> R.drawable.flag_af
        FlagIso.AX -> R.drawable.flag_ax
        FlagIso.AL -> R.drawable.flag_al
        FlagIso.DZ -> R.drawable.flag_dz
        FlagIso.AS -> R.drawable.flag_as
        FlagIso.AD -> R.drawable.flag_ad
        FlagIso.AO -> R.drawable.flag_ao
        FlagIso.AI -> R.drawable.flag_ai
        FlagIso.AQ -> R.drawable.flag_aq
        FlagIso.AG -> R.drawable.flag_ag
        FlagIso.AR -> R.drawable.flag_ar
        FlagIso.AM -> R.drawable.flag_am
        FlagIso.AW -> R.drawable.flag_aw
        FlagIso.AU -> R.drawable.flag_au
        FlagIso.AT -> R.drawable.flag_at
        FlagIso.AZ -> R.drawable.flag_az
        FlagIso.BS -> R.drawable.flag_bs
        FlagIso.BH -> R.drawable.flag_bh
        FlagIso.BD -> R.drawable.flag_bd
        FlagIso.BB -> R.drawable.flag_bb
        FlagIso.BY -> R.drawable.flag_by
        FlagIso.BE -> R.drawable.flag_be
        FlagIso.BZ -> R.drawable.flag_bz
        FlagIso.BJ -> R.drawable.flag_bj
        FlagIso.BM -> R.drawable.flag_bm
        FlagIso.BT -> R.drawable.flag_bt
        FlagIso.BO -> R.drawable.flag_bo
        FlagIso.BQ -> R.drawable.flag_bq
        FlagIso.BA -> R.drawable.flag_ba
        FlagIso.BW -> R.drawable.flag_bw
        FlagIso.BR -> R.drawable.flag_br
        FlagIso.BN -> R.drawable.flag_bn
        FlagIso.BG -> R.drawable.flag_bg
        FlagIso.BF -> R.drawable.flag_bf
        FlagIso.BI -> R.drawable.flag_bi
        FlagIso.CV -> R.drawable.flag_cv
        FlagIso.KH -> R.drawable.flag_kh
        FlagIso.CM -> R.drawable.flag_cm
        FlagIso.CA -> R.drawable.flag_ca
        FlagIso.KY -> R.drawable.flag_ky
        FlagIso.CF -> R.drawable.flag_cf
        FlagIso.TD -> R.drawable.flag_td
        FlagIso.CL -> R.drawable.flag_cl
        FlagIso.CN -> R.drawable.flag_cn
        FlagIso.CX -> R.drawable.flag_cx
        FlagIso.CC -> R.drawable.flag_cc
        FlagIso.CO -> R.drawable.flag_co
        FlagIso.KM -> R.drawable.flag_km
        FlagIso.CG -> R.drawable.flag_cg
        FlagIso.CD -> R.drawable.flag_cd
        FlagIso.CK -> R.drawable.flag_ck
        FlagIso.CR -> R.drawable.flag_cr
        FlagIso.CI -> R.drawable.flag_ci
        FlagIso.HR -> R.drawable.flag_hr
        FlagIso.CU -> R.drawable.flag_cu
        FlagIso.CW -> R.drawable.flag_cw
        FlagIso.CY -> R.drawable.flag_cy
        FlagIso.CZ -> R.drawable.flag_cz
        FlagIso.DK -> R.drawable.flag_dk
        FlagIso.DJ -> R.drawable.flag_dj
        FlagIso.DM -> R.drawable.flag_dm
        FlagIso.DO -> R.drawable.flag_do
        FlagIso.EC -> R.drawable.flag_ec
        FlagIso.EG -> R.drawable.flag_eg
        FlagIso.SV -> R.drawable.flag_sv
        FlagIso.GQ -> R.drawable.flag_gq
        FlagIso.ER -> R.drawable.flag_er
        FlagIso.EE -> R.drawable.flag_ee
        FlagIso.SZ -> R.drawable.flag_sz
        FlagIso.ET -> R.drawable.flag_et
        FlagIso.FK -> R.drawable.flag_fk
        FlagIso.FO -> R.drawable.flag_fo
        FlagIso.FJ -> R.drawable.flag_fj
        FlagIso.FI -> R.drawable.flag_fi
        FlagIso.FR -> R.drawable.flag_fr
        FlagIso.GF -> R.drawable.flag_gf
        FlagIso.PF -> R.drawable.flag_pf
        FlagIso.GA -> R.drawable.flag_ga
        FlagIso.GM -> R.drawable.flag_gm
        FlagIso.GE -> R.drawable.flag_ge
        FlagIso.DE -> R.drawable.flag_de
        FlagIso.GH -> R.drawable.flag_gh
        FlagIso.GI -> R.drawable.flag_gi
        FlagIso.GR -> R.drawable.flag_gr
        FlagIso.GL -> R.drawable.flag_gl
        FlagIso.GD -> R.drawable.flag_gd
        FlagIso.GP -> R.drawable.flag_gp
        FlagIso.GU -> R.drawable.flag_gu
        FlagIso.GT -> R.drawable.flag_gt
        FlagIso.GG -> R.drawable.flag_gg
        FlagIso.GN -> R.drawable.flag_gn
        FlagIso.GW -> R.drawable.flag_gw
        FlagIso.GY -> R.drawable.flag_gy
        FlagIso.HT -> R.drawable.flag_ht
        FlagIso.HN -> R.drawable.flag_hn
        FlagIso.HK -> R.drawable.flag_hk
        FlagIso.HU -> R.drawable.flag_hu
        FlagIso.IS -> R.drawable.flag_is
        FlagIso.IN -> R.drawable.flag_in
        FlagIso.ID -> R.drawable.flag_id
        FlagIso.IR -> R.drawable.flag_ir
        FlagIso.IQ -> R.drawable.flag_iq
        FlagIso.IE -> R.drawable.flag_ie
        FlagIso.IM -> R.drawable.flag_im
        FlagIso.IL -> R.drawable.flag_il
        FlagIso.IT -> R.drawable.flag_it
        FlagIso.JM -> R.drawable.flag_jm
        FlagIso.JP -> R.drawable.flag_jp
        FlagIso.JE -> R.drawable.flag_je
        FlagIso.JO -> R.drawable.flag_jo
        FlagIso.KZ -> R.drawable.flag_kz
        FlagIso.KE -> R.drawable.flag_ke
        FlagIso.KI -> R.drawable.flag_ki
        FlagIso.KP -> R.drawable.flag_kp
        FlagIso.KR -> R.drawable.flag_kr
        FlagIso.KW -> R.drawable.flag_kw
        FlagIso.KG -> R.drawable.flag_kg
        FlagIso.LA -> R.drawable.flag_la
        FlagIso.LV -> R.drawable.flag_lv
        FlagIso.LB -> R.drawable.flag_lb
        FlagIso.LS -> R.drawable.flag_ls
        FlagIso.LR -> R.drawable.flag_lr
        FlagIso.LY -> R.drawable.flag_ly
        FlagIso.LI -> R.drawable.flag_li
        FlagIso.LT -> R.drawable.flag_lt
        FlagIso.LU -> R.drawable.flag_lu
        FlagIso.MO -> R.drawable.flag_mo
        FlagIso.MG -> R.drawable.flag_mg
        FlagIso.MW -> R.drawable.flag_mw
        FlagIso.MY -> R.drawable.flag_my
        FlagIso.MV -> R.drawable.flag_mv
        FlagIso.ML -> R.drawable.flag_ml
        FlagIso.MT -> R.drawable.flag_mt
        FlagIso.MH -> R.drawable.flag_mh
        FlagIso.MQ -> R.drawable.flag_mq
        FlagIso.MR -> R.drawable.flag_mr
        FlagIso.MU -> R.drawable.flag_mu
        FlagIso.YT -> R.drawable.flag_yt
        FlagIso.MX -> R.drawable.flag_mx
        FlagIso.FM -> R.drawable.flag_fm
        FlagIso.MD -> R.drawable.flag_md
        FlagIso.MC -> R.drawable.flag_mc
        FlagIso.MN -> R.drawable.flag_mn
        FlagIso.ME -> R.drawable.flag_me
        FlagIso.MS -> R.drawable.flag_ms
        FlagIso.MA -> R.drawable.flag_ma
        FlagIso.MZ -> R.drawable.flag_mz
        FlagIso.MM -> R.drawable.flag_mm
        FlagIso.NA -> R.drawable.flag_na
        FlagIso.NR -> R.drawable.flag_nr
        FlagIso.NP -> R.drawable.flag_np
        FlagIso.NL -> R.drawable.flag_nl
        FlagIso.NC -> R.drawable.flag_nc
        FlagIso.NZ -> R.drawable.flag_nz
        FlagIso.NI -> R.drawable.flag_ni
        FlagIso.NE -> R.drawable.flag_ne
        FlagIso.NG -> R.drawable.flag_ng
        FlagIso.NU -> R.drawable.flag_nu
        FlagIso.NF -> R.drawable.flag_nf
        FlagIso.MK -> R.drawable.flag_mk
        FlagIso.NO -> R.drawable.flag_no
        FlagIso.OM -> R.drawable.flag_om
        FlagIso.PK -> R.drawable.flag_pk
        FlagIso.PW -> R.drawable.flag_pw
        FlagIso.PS -> R.drawable.flag_ps
        FlagIso.PA -> R.drawable.flag_pa
        FlagIso.PG -> R.drawable.flag_pg
        FlagIso.PY -> R.drawable.flag_py
        FlagIso.PE -> R.drawable.flag_pe
        FlagIso.PH -> R.drawable.flag_ph
        FlagIso.PN -> R.drawable.flag_pn
        FlagIso.PL -> R.drawable.flag_pl
        FlagIso.PT -> R.drawable.flag_pt
        FlagIso.PR -> R.drawable.flag_pr
        FlagIso.QA -> R.drawable.flag_qa
        FlagIso.RE -> R.drawable.flag_re
        FlagIso.RO -> R.drawable.flag_ro
        FlagIso.RU -> R.drawable.flag_ru
        FlagIso.RW -> R.drawable.flag_rw
        FlagIso.BL -> R.drawable.flag_bl
        FlagIso.SH -> R.drawable.flag_sh
        FlagIso.KN -> R.drawable.flag_kn
        FlagIso.LC -> R.drawable.flag_lc
        FlagIso.MF -> R.drawable.flag_mf
        FlagIso.PM -> R.drawable.flag_pm
        FlagIso.VC -> R.drawable.flag_vc
        FlagIso.WS -> R.drawable.flag_ws
        FlagIso.SM -> R.drawable.flag_sm
        FlagIso.ST -> R.drawable.flag_st
        FlagIso.SA -> R.drawable.flag_sa
        FlagIso.SN -> R.drawable.flag_sn
        FlagIso.RS -> R.drawable.flag_rs
        FlagIso.SC -> R.drawable.flag_sc
        FlagIso.SL -> R.drawable.flag_sl
        FlagIso.SG -> R.drawable.flag_sg
        FlagIso.SX -> R.drawable.flag_sx
        FlagIso.SK -> R.drawable.flag_sk
        FlagIso.SI -> R.drawable.flag_si
        FlagIso.SB -> R.drawable.flag_sb
        FlagIso.SO -> R.drawable.flag_so
        FlagIso.ZA -> R.drawable.flag_za
        FlagIso.GS -> R.drawable.flag_gs
        FlagIso.SS -> R.drawable.flag_ss
        FlagIso.ES -> R.drawable.flag_es
        FlagIso.LK -> R.drawable.flag_lk
        FlagIso.SD -> R.drawable.flag_sd
        FlagIso.SR -> R.drawable.flag_sr
        FlagIso.SJ -> R.drawable.flag_sj
        FlagIso.SE -> R.drawable.flag_se
        FlagIso.CH -> R.drawable.flag_ch
        FlagIso.SY -> R.drawable.flag_sy
        FlagIso.TW -> R.drawable.flag_tw
        FlagIso.TJ -> R.drawable.flag_tj
        FlagIso.TZ -> R.drawable.flag_tz
        FlagIso.TH -> R.drawable.flag_th
        FlagIso.TL -> R.drawable.flag_tl
        FlagIso.TG -> R.drawable.flag_tg
        FlagIso.TK -> R.drawable.flag_tk
        FlagIso.TO -> R.drawable.flag_to
        FlagIso.TT -> R.drawable.flag_tt
        FlagIso.TN -> R.drawable.flag_tn
        FlagIso.TR -> R.drawable.flag_tr
        FlagIso.TM -> R.drawable.flag_tm
        FlagIso.TC -> R.drawable.flag_tc
        FlagIso.TV -> R.drawable.flag_tv
        FlagIso.UG -> R.drawable.flag_ug
        FlagIso.UA -> R.drawable.flag_ua
        FlagIso.AE -> R.drawable.flag_ae
        FlagIso.GB -> R.drawable.flag_gb
        FlagIso.US -> R.drawable.flag_us
        FlagIso.UY -> R.drawable.flag_uy
        FlagIso.UZ -> R.drawable.flag_uz
        FlagIso.VU -> R.drawable.flag_vu
        FlagIso.VE -> R.drawable.flag_ve
        FlagIso.VN -> R.drawable.flag_vn
        FlagIso.VG -> R.drawable.flag_vg
        FlagIso.VI -> R.drawable.flag_vi
        FlagIso.WF -> R.drawable.flag_wf
        FlagIso.EH -> R.drawable.flag_eh
        FlagIso.YE -> R.drawable.flag_ye
        FlagIso.ZM -> R.drawable.flag_zm
        FlagIso.ZW -> R.drawable.flag_zw
        FlagIso.XK -> R.drawable.flag_xk
        else -> R.drawable.flag_us
    }
}