package com.application.echo.ui.components.flags

object FlagIso {
    val AC = "ac"; val AF = "af"; val AX = "ax"; val AL = "al"; val DZ = "dz"
    val AS = "as"; val AD = "ad"; val AO = "ao"; val AI = "ai"
    val AQ = "aq"; val AG = "ag"; val AR = "ar"; val AM = "am"
    val AW = "aw"; val AU = "au"; val AT = "at"; val AZ = "az"
    val BS = "bs"; val BH = "bh"; val BD = "bd"; val BB = "bb"
    val BY = "by"; val BE = "be"; val BZ = "bz"; val BJ = "bj"
    val BM = "bm"; val BT = "bt"; val BO = "bo"; val BQ = "bq"
    val BA = "ba"; val BW = "bw"; val BR = "br"; val BN = "bn"
    val BG = "bg"; val BF = "bf"; val BI = "bi"; val CV = "cv"
    val KH = "kh"; val CM = "cm"; val CA = "ca"; val KY = "ky"
    val CF = "cf"; val TD = "td"; val CL = "cl"; val CN = "cn"
    val CX = "cx"; val CC = "cc"; val CO = "co"; val KM = "km"
    val CG = "cg"; val CD = "cd"; val CK = "ck"; val CR = "cr"
    val CI = "ci"; val HR = "hr"; val CU = "cu"; val CW = "cw"
    val CY = "cy"; val CZ = "cz"; val DK = "dk"; val DJ = "dj"
    val DM = "dm"; val DO = "do"; val EC = "ec"; val EG = "eg"
    val SV = "sv"; val GQ = "gq"; val ER = "er"; val EE = "ee"
    val SZ = "sz"; val ET = "et"; val FK = "fk"; val FO = "fo"
    val FJ = "fj"; val FI = "fi"; val FR = "fr"; val GF = "gf"
    val PF = "pf"; val GA = "ga"; val GM = "gm"; val GE = "ge"
    val DE = "de"; val GH = "gh"; val GI = "gi"; val GR = "gr"
    val GL = "gl"; val GD = "gd"; val GP = "gp"; val GU = "gu"
    val GT = "gt"; val GG = "gg"; val GN = "gn"; val GW = "gw"
    val GY = "gy"; val HT = "ht"; val HN = "hn"; val HK = "hk"
    val HU = "hu"; val IS = "is"; val IN = "in"; val ID = "id"
    val IO = "io"; val IR = "ir"; val IQ = "iq"; val IE = "ie"; val IM = "im"
    val IL = "il"; val IT = "it"; val JM = "jm"; val JP = "jp"
    val JE = "je"; val JO = "jo"; val KZ = "kz"; val KE = "ke"
    val KI = "ki"; val KP = "kp"; val KR = "kr"; val KW = "kw"
    val KG = "kg"; val LA = "la"; val LV = "lv"; val LB = "lb"
    val LS = "ls"; val LR = "lr"; val LY = "ly"; val LI = "li"
    val LT = "lt"; val LU = "lu"; val MO = "mo"; val MG = "mg"
    val MW = "mw"; val MY = "my"; val MV = "mv"; val ML = "ml"
    val MP = "mp"; val MT = "mt"; val MH = "mh"; val MQ = "mq"; val MR = "mr"
    val MU = "mu"; val YT = "yt"; val MX = "mx"; val FM = "fm"
    val MD = "md"; val MC = "mc"; val MN = "mn"; val ME = "me"
    val MS = "ms"; val MA = "ma"; val MZ = "mz"; val MM = "mm"
    val NA = "na"; val NR = "nr"; val NP = "np"; val NL = "nl"
    val NC = "nc"; val NZ = "nz"; val NI = "ni"; val NE = "ne"
    val NG = "ng"; val NU = "nu"; val NF = "nf"; val MK = "mk"
    val NO = "no"; val OM = "om"; val PK = "pk"; val PW = "pw"
    val PS = "ps"; val PA = "pa"; val PG = "pg"; val PY = "py"
    val PE = "pe"; val PH = "ph"; val PN = "pn"; val PL = "pl"
    val PT = "pt"; val PR = "pr"; val QA = "qa"; val RE = "re"
    val RO = "ro"; val RU = "ru"; val RW = "rw"; val BL = "bl"
    val SH = "sh"; val KN = "kn"; val LC = "lc"; val MF = "mf"
    val PM = "pm"; val VC = "vc"; val WS = "ws"; val SM = "sm"
    val ST = "st"; val SA = "sa"; val SN = "sn"; val RS = "rs"
    val SC = "sc"; val SL = "sl"; val SG = "sg"; val SX = "sx"
    val SK = "sk"; val SI = "si"; val SB = "sb"; val SO = "so"
    val ZA = "za"; val GS = "gs"; val SS = "ss"; val ES = "es"
    val LK = "lk"; val SD = "sd"; val SR = "sr"; val SJ = "sj"
    val SE = "se"; val CH = "ch"; val SY = "sy"; val TW = "tw"
    val TJ = "tj"; val TZ = "tz"; val TH = "th"; val TL = "tl"
    val TG = "tg"; val TK = "tk"; val TO = "to"; val TT = "tt"
    val TN = "tn"; val TR = "tr"; val TM = "tm"; val TC = "tc"
    val TV = "tv"; val UG = "ug"; val UA = "ua"; val AE = "ae"
    val GB = "gb"; val US = "us"; val UY = "uy"; val UZ = "uz"
    val VA = "va"; val VU = "vu"; val VE = "ve"; val VN = "vn"; val VG = "vg"
    val VI = "vi"; val WF = "wf"; val EH = "eh"; val YE = "ye"
    val ZM = "zm"; val ZW = "zw"; val XK = "xk"
}