package com.application.echo.ui.design.shape

import android.graphics.drawable.shapes.Shape
import androidx.compose.foundation.shape.CornerBasedShape

data class EchoShapes(
    val card: CornerBasedShape,
    val cardSmall: CornerBasedShape,
    val cardLarge: CornerBasedShape,
    val button: CornerBasedShape,
    val buttonSmall: CornerBasedShape,
    val buttonLarge: CornerBasedShape,
    val input: CornerBasedShape,
    val inputMultiline: CornerBasedShape,
    val searchBar: CornerBasedShape,
    val chip: CornerBasedShape,
    val tag: CornerBasedShape,
    val badge: CornerBasedShape,
    val dialog: CornerBasedShape,
    val bottomSheet: CornerBasedShape,
    val sideSheet: CornerBasedShape,
    val popover: CornerBasedShape,
    val tooltip: CornerBasedShape,
    val banner: CornerBasedShape,
    val dropdown: CornerBasedShape,
    val snackbar: CornerBasedShape,
    val notification: CornerBasedShape,
    val fab: CornerBasedShape,
    val fabSmall: CornerBasedShape,
    val fabExtended: CornerBasedShape,
    val progressIndicator: CornerBasedShape,
    val progressTrack: CornerBasedShape,
    val skeleton: CornerBasedShape,
    val checkbox: CornerBasedShape,
    val toggleTrack: CornerBasedShape,
    val sliderThumb: CornerBasedShape,
    val navigationBar: CornerBasedShape,
    val navigationRailItem: CornerBasedShape,
    val tabIndicator: CornerBasedShape,
    val avatar: CornerBasedShape,
    val avatarSquare: CornerBasedShape,
    val imageThumbnail: CornerBasedShape,
    val imageHero: CornerBasedShape,
    val icon: CornerBasedShape,
    val iconLarge: CornerBasedShape,
)