package com.application.echo.ui.design.shape

import androidx.compose.ui.unit.dp


internal val echoShapes = EchoShapes(
    card = SquircleCornerShape(28.dp),
    cardSmall = SquircleCornerShape(20.dp),
    cardLarge = SquircleCornerShape(36.dp),
    button = SquircleCornerShape(20.dp),
    buttonSmall = SquircleCornerShape(16.dp),
    buttonLarge = SquircleCornerShape(24.dp),
    input = SquircleCornerShape(18.dp),
    inputMultiline = SquircleCornerShape(20.dp),
    searchBar = SquircleCornerShape(percent = 50),
    chip = SquircleCornerShape(percent = 50),
    tag = SquircleCornerShape(12.dp),
    badge = SquircleCornerShape(percent = 50),
    dialog = SquircleCornerShape(36.dp),
    bottomSheet = SquircleCornerShape(topStart = 40.dp, topEnd = 40.dp),
    sideSheet = SquircleCornerShape(topStart = 36.dp, bottomStart = 36.dp),
    popover = SquircleCornerShape(24.dp),
    tooltip = SquircleCornerShape(16.dp),
    banner = SquircleCornerShape(24.dp),
    dropdown = SquircleCornerShape(20.dp),
    snackbar = SquircleCornerShape(24.dp),
    notification = SquircleCornerShape(24.dp),
    fab = SquircleCornerShape(percent = 50),
    fabSmall = SquircleCornerShape(percent = 50),
    fabExtended = SquircleCornerShape(percent = 50),
    progressIndicator = SquircleCornerShape(percent = 50),
    progressTrack = SquircleCornerShape(percent = 50),
    skeleton = SquircleCornerShape(12.dp),
    checkbox = SquircleCornerShape(8.dp),
    toggleTrack = SquircleCornerShape(percent = 50),
    sliderThumb = SquircleCornerShape(percent = 50),
    navigationBar = SquircleCornerShape(topStart = 32.dp, topEnd = 32.dp),
    navigationRailItem = SquircleCornerShape(percent = 50),
    tabIndicator = SquircleCornerShape(percent = 50),
    avatar = SquircleCornerShape(percent = 50),
    avatarSquare = SquircleCornerShape(24.dp),
    imageThumbnail = SquircleCornerShape(24.dp),
    imageHero = SquircleCornerShape(32.dp),
    icon = SquircleCornerShape(14.dp),
    iconLarge = SquircleCornerShape(22.dp),
)